services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: rrDb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    command: [
      "--bind-address=0.0.0.0"
    ]

volumes:
  mariadb_data:
