services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: rrDb
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
